import {
  BadgeCheck,
  Bell,
  Briefcase,
  Building,
  Building2,
  Cctv,
  ClipboardCheck,
  Clock,
  GraduationCap,
  HardHat,
  Headphones,
  Hotel,
  House,
  KeyRound,
  LifeBuoy,
  MapPin,
  MonitorPlay,
  Package,
  PencilRuler,
  Receipt,
  RefreshCw,
  ScanLine,
  ScanSearch,
  ShieldCheck,
  Smartphone,
  Smile,
  Sparkles,
  Stethoscope,
  Store,
  Utensils,
  Warehouse,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const iconRegistry: Record<string, LucideIcon> = {
  BadgeCheck,
  Bell,
  Briefcase,
  Building,
  Building2,
  Cctv,
  ClipboardCheck,
  Clock,
  GraduationCap,
  HardHat,
  Headphones,
  Hotel,
  House,
  KeyRound,
  LifeBuoy,
  MapPin,
  MonitorPlay,
  Package,
  PencilRuler,
  Receipt,
  RefreshCw,
  ScanLine,
  ScanSearch,
  ShieldCheck,
  Smartphone,
  Smile,
  Sparkles,
  Stethoscope,
  Store,
  Utensils,
  Warehouse,
  Wrench,
};

// Content stores icons as string names; resolve to a Lucide component, with a safe fallback.
export function resolveIcon(name: string): LucideIcon {
  return iconRegistry[name] ?? ShieldCheck;
}
