import type { Industry } from "@/types";

export const industries: Industry[] = [
  {
    slug: "retail",
    name: "Retail",
    challenge: "Shrinkage, disputes, and after-hours break-ins.",
    solution: "Entrance, till, and floor coverage with clear footage for incident review.",
    icon: "Store",
    outcome: "Clear footage when a loss or dispute needs settling.",
    imageId: "ind-retail",
  },
  {
    slug: "warehousing-and-logistics",
    name: "Warehousing & Logistics",
    challenge: "Large floor areas, loading docks, and high-value inventory.",
    solution: "Wide-area and dock coverage with retention sized for investigations.",
    icon: "Warehouse",
    outcome: "Dock and aisle coverage kept for the reviews that matter.",
    imageId: "ind-warehousing",
  },
  {
    slug: "hospitality",
    name: "Hospitality",
    challenge: "Guest safety, common areas, and liability exposure.",
    solution: "Discreet coverage of entrances, lobbies, and back-of-house.",
    icon: "Hotel",
    outcome: "Discreet coverage across guest and staff areas.",
    imageId: "ind-hospitality",
  },
  {
    slug: "healthcare-and-clinics",
    name: "Healthcare & Clinics",
    challenge: "Patient safety, restricted areas, and privacy boundaries.",
    solution: "Targeted placement at entrances and restricted areas, planned around private zones.",
    icon: "Stethoscope",
    outcome: "Coverage planned around the areas that need it — not the ones that don't.",
    imageId: "ind-healthcare",
  },
  {
    slug: "education",
    name: "Education",
    challenge: "Multiple buildings, entrances, and grounds to monitor.",
    solution: "Coverage across entrances, hallways, and grounds, recorded to one system.",
    icon: "GraduationCap",
    outcome: "Entrances and grounds on one recorded system you can review.",
    imageId: "ind-education",
  },
  {
    slug: "multi-residential-and-condos",
    name: "Multi-Residential & Condos",
    challenge: "Shared entries, parking, and amenity spaces.",
    solution: "Common-area coverage with footage available to property management.",
    icon: "Building",
    outcome: "Common-area footage your property manager can pull when needed.",
    imageId: "ind-multi-residential",
  },
  {
    slug: "construction-sites",
    name: "Construction Sites",
    challenge: "Theft of tools and materials on unsecured sites.",
    solution: "Deterrent coverage of access points and storage areas.",
    icon: "HardHat",
    outcome: "A visible deterrent that makes an open site a harder target.",
    imageId: "ind-construction",
  },
  {
    slug: "offices",
    name: "Offices",
    challenge: "Access control, after-hours security, and staff safety.",
    solution: "Entrance and interior coverage tied to recording and remote viewing.",
    icon: "Briefcase",
    outcome: "Entrances and floors recorded, and viewable from your phone anywhere.",
    imageId: "ind-offices",
  },
];
