// Generated by scripts/gen-legal-content.mjs from scripts/legal-content-data.json — edit there, not here.
import type { LegalDocument } from "@/types";
import { legalLastUpdated } from "./legal-facts";

export const accessibilityStatement: LegalDocument = {
  title: "Accessibility Statement",
  summary: "This statement explains how we work to make this website accessible to people of all abilities, the standard we follow, what we have done, known limitations, and how to reach us.",
  lastUpdated: legalLastUpdated,
  sections: [
    {
      id: "commitment",
      heading: "Our commitment to accessibility",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              fact: "entityName"
            },
            {
              text: " is committed to providing an accessible and inclusive digital experience for people of all abilities. We want everyone — including people who use screen readers, keyboard navigation, screen magnification, or other assistive technologies — to be able to learn about our security camera and CCTV installation services, request a quote, and reach us without barriers."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "Accessibility is not a one-time project for us. We treat it as an ongoing part of how we design, build, and maintain this website, and we work to improve it as standards evolve and as we receive feedback from visitors."
            }
          ]
        },
        {
          kind: "note",
          runs: [
            {
              text: "This statement applies to this website. Our conformance claims are based on our own internal review and ongoing testing rather than a formal third-party audit."
            }
          ]
        }
      ]
    },
    {
      id: "standard",
      heading: "Conformance standard",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "We build this site to meet the "
            },
            {
              text: "Web Content Accessibility Guidelines (WCAG) 2.2 at Level AA",
              href: "https://www.w3.org/TR/WCAG22/"
            },
            {
              text: ". WCAG is the internationally recognized standard for making web content more accessible to people with a wide range of disabilities, including visual, auditory, physical, speech, cognitive, and neurological disabilities."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "We use WCAG 2.2 Level AA, together with the accessibility principles set out in the Accessibility for Ontarians with Disabilities Act (AODA) and its Integrated Accessibility Standards Regulation, as our working benchmark for this website — regardless of the province where we are registered. Accessibility laws and standards may also apply in our registered province ("
            },
            {
              fact: "province"
            },
            {
              text: "), in other provinces, and at the federal level, and we monitor these as part of our ongoing work."
            }
          ]
        }
      ]
    },
    {
      id: "measures",
      heading: "What we have done",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "We have built accessibility into the design and code of this site. Measures we have taken include:"
            }
          ]
        },
        {
          kind: "list",
          items: [
            [
              {
                text: "Using semantic HTML structure with proper headings and landmark regions, so assistive technologies can understand and navigate the page layout."
              }
            ],
            [
              {
                text: "Implementing keyboard operability across links, buttons, and the quote/contact form, so the site can be used without a mouse."
              }
            ],
            [
              {
                text: "Providing visible focus indicators, so keyboard users can see which element is currently selected."
              }
            ],
            [
              {
                text: "Working to maintain colour contrast between text and background that meets WCAG 2.2 Level AA contrast ratios."
              }
            ],
            [
              {
                text: "Adding descriptive alternative text to meaningful images, so screen-reader users receive the information conveyed visually."
              }
            ],
            [
              {
                text: "Labelling form fields clearly and surfacing helpful error messages on our quote and contact form, so it is easier to complete with assistive technology."
              }
            ],
            [
              {
                text: "Respecting the operating-system \"reduced motion\" preference, so animations are minimized for visitors who are sensitive to motion."
              }
            ],
            [
              {
                text: "Using a responsive layout that aims to support text resizing and browser zoom up to 200% without loss of content or functionality, across desktop, tablet, and mobile screens."
              }
            ]
          ]
        }
      ]
    },
    {
      id: "limitations",
      heading: "Known limitations",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "Despite our efforts, some parts of the site may not yet fully conform to WCAG 2.2 Level AA. Accessibility is an ongoing process, and we are actively working to identify and resolve issues as we find them."
            }
          ]
        },
        {
          kind: "list",
          items: [
            [
              {
                text: "Third-party embedded content — for example, an embedded "
              },
              {
                text: "Google Maps",
                href: "https://policies.google.com/privacy"
              },
              {
                text: " service-area map — is controlled by an external provider, and we cannot guarantee that it fully meets the same accessibility standards as the rest of our site."
              }
            ],
            [
              {
                text: "Bot-protection on our forms is provided by "
              },
              {
                text: "Cloudflare Turnstile",
                href: "https://www.cloudflare.com/privacypolicy/"
              },
              {
                text: ", a third-party widget. Like other external components, it may have accessibility limitations we cannot directly fix."
              }
            ]
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "Where a third-party component creates a barrier, we will do our best to provide the same information or service through an alternative method. If you encounter content you cannot access, please tell us — see the section below — and we will help."
            }
          ]
        }
      ]
    },
    {
      id: "feedback-contact",
      heading: "Feedback, contact, and alternative formats",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "We welcome your feedback on the accessibility of this website. If you run into an accessibility barrier, or if you would like any information on this site provided in an alternative format (for example, large print, plain text, accessible electronic text, or read over the phone), please contact us and we will be glad to help. Tell us the format and accessible medium that works best for you, and we will work with you to provide it."
            }
          ]
        },
        {
          kind: "definitions",
          entries: [
            {
              term: "Email",
              runs: [
                {
                  fact: "privacyOfficerEmail"
                }
              ]
            },
            {
              term: "Phone",
              runs: [
                {
                  fact: "privacyOfficerPhone"
                }
              ]
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "If you prefer, you can also reach us through the "
            },
            {
              text: "contact form",
              href: "/contact"
            },
            {
              text: " on this website. When you get in touch, it helps to tell us the page you were on, what you were trying to do, and the assistive technology or browser you were using, so we can resolve the issue more quickly."
            }
          ]
        },
        {
          kind: "note",
          runs: [
            {
              text: "We aim to acknowledge accessibility feedback promptly and to provide requested information in an alternative format within a reasonable timeframe. There is no charge for requesting an alternative format."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "If you are not satisfied with how we have responded to your accessibility feedback, please let us know so we can try again to put it right. You may also contact the Office of the Privacy Commissioner of Canada or the accessibility regulator in your province about your concerns. The Office of the Privacy Commissioner of Canada can be reached at "
            },
            {
              text: "www.priv.gc.ca",
              href: "https://www.priv.gc.ca/"
            },
            {
              text: " or "
            },
            {
              text: "1-800-282-1376",
              href: "tel:1-800-282-1376"
            },
            {
              text: "."
            }
          ]
        }
      ]
    }
  ]
};
