// Generated by scripts/gen-legal-content.mjs from scripts/legal-content-data.json — edit there, not here.
import type { LegalDocument } from "@/types";
import { legalLastUpdated } from "./legal-facts";

export const privacyPolicy: LegalDocument = {
  title: "Privacy Policy",
  summary: "How we collect, use, protect, and share the personal information you provide through this website and its quote and contact form, and the privacy rights you have under Canadian law.",
  lastUpdated: legalLastUpdated,
  sections: [
    {
      id: "introduction",
      heading: "Introduction",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              fact: "entityName"
            },
            {
              text: " (\"we\", \"us\", or \"our\") supplies and professionally installs security camera and CCTV systems for commercial and residential properties across Canada. We respect your privacy and are committed to protecting the personal information you entrust to us."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "This Privacy Policy explains how we collect, use, disclose, and safeguard personal information through our marketing website and the quote and contact form on it. It does not cover the separate written agreements that govern our supply, installation, and warranty services, which set out their own terms."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "We handle personal information in accordance with Canada's federal privacy law, the "
            },
            {
              text: "Personal Information Protection and Electronic Documents Act (PIPEDA)",
              href: "https://www.priv.gc.ca/en/privacy-topics/privacy-laws-in-canada/the-personal-information-protection-and-electronic-documents-act-pipeda/"
            },
            {
              text: ". Depending on where you live, a provincial privacy law, such as those in Quebec, British Columbia, or Alberta, may also apply to how your information is handled, and we follow those requirements where they do. We operate from "
            },
            {
              fact: "province"
            },
            {
              text: "."
            }
          ]
        }
      ]
    },
    {
      id: "information-we-collect",
      heading: "Personal Information We Collect",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "We collect only the personal information we reasonably need to respond to you and to operate this website. This falls into two categories."
            }
          ]
        },
        {
          kind: "subheading",
          text: "Information you give us"
        },
        {
          kind: "definitions",
          entries: [
            {
              term: "Name",
              runs: [
                {
                  text: "The name you provide so we can address you and identify your request."
                }
              ]
            },
            {
              term: "Email address",
              runs: [
                {
                  text: "Used to reply to your enquiry, send your quote, and confirm appointments."
                }
              ]
            },
            {
              term: "Phone number",
              runs: [
                {
                  text: "Used to reach you about your request and to schedule a site assessment or installation."
                }
              ]
            },
            {
              term: "Property type",
              runs: [
                {
                  text: "Whether the property is commercial or residential, so we can scope the right system for you."
                }
              ]
            },
            {
              term: "Property address and message details",
              runs: [
                {
                  text: "The address or location of the property and anything else you choose to tell us in the message field, so we can understand your needs and prepare an accurate estimate."
                }
              ]
            }
          ]
        },
        {
          kind: "subheading",
          text: "Information collected automatically"
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "When you visit the site, and only as described in the Cookies and Tracking section below, we may automatically collect limited technical information, including:"
            }
          ]
        },
        {
          kind: "list",
          ordered: false,
          items: [
            [
              {
                text: "your IP address;"
              }
            ],
            [
              {
                text: "your device type, operating system, and browser type;"
              }
            ],
            [
              {
                text: "the pages you view and how you navigate the site, collected through analytics; and"
              }
            ],
            [
              {
                text: "cookies and similar identifiers, as explained below."
              }
            ]
          ]
        },
        {
          kind: "note",
          runs: [
            {
              text: "We do not ask for sensitive information such as government IDs, financial account numbers, or payment card details through this website. Please do not include sensitive details in the form's free-text fields."
            }
          ]
        }
      ]
    },
    {
      id: "how-we-use",
      heading: "Why We Collect It and How We Use It",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "We identify the purposes for collecting your personal information at or before the time we collect it. We use the information described above to:"
            }
          ]
        },
        {
          kind: "list",
          ordered: false,
          items: [
            [
              {
                text: "respond to your quote requests and enquiries and prepare estimates;"
              }
            ],
            [
              {
                text: "schedule and carry out site assessments and installations;"
              }
            ],
            [
              {
                text: "communicate with you about your request, including follow-up questions and appointment details;"
              }
            ],
            [
              {
                text: "operate, maintain, secure, and improve the website, including protecting the form against spam and abuse; and"
              }
            ],
            [
              {
                text: "meet our legal, regulatory, and record-keeping obligations."
              }
            ]
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "We will not use your personal information for a new purpose that is not described here without first identifying that purpose and, where required, obtaining your consent. The estimates and quotes we provide are not binding contracts; the supply and installation of any system is governed by a separate written agreement."
            }
          ]
        }
      ]
    },
    {
      id: "consent",
      heading: "Consent",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "When you submit the quote or contact form, you give us your express consent to collect and use the information in that form for the purposes described in this policy. Submitting the form is a deliberate step you take to ask us to contact you."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "For non-essential website analytics, we rely on your opt-in consent. Analytics are off by default and do not load until you affirmatively accept them through the cookie banner. Until you accept, we do not load them, which means we treat your express acceptance as the basis for any non-essential tracking."
            }
          ]
        },
        {
          kind: "subheading",
          text: "Marketing email and CASL"
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "Replying to your enquiry or sending your quote is not marketing. If we ever send you commercial or marketing email, we will do so only in line with Canada's Anti-Spam Legislation (CASL): we will obtain your express consent first, every message will clearly identify us, and each one will include a working unsubscribe option that we will honour promptly."
            }
          ]
        },
        {
          kind: "subheading",
          text: "Withdrawing your consent"
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "You may withdraw your consent at any time, subject to legal or contractual restrictions and reasonable notice, by contacting our Privacy Officer using the details in the Contact section. You can decline or change your analytics choice at any time through the cookie banner. If you withdraw consent, we may no longer be able to respond to your request or provide the service you asked for, and we will explain the likely consequences before you decide."
            }
          ]
        }
      ]
    },
    {
      id: "cookies-tracking",
      heading: "Cookies and Tracking",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "Cookies are small files stored on your device. We use a small number of cookies and similar technologies, which fall into two groups."
            }
          ]
        },
        {
          kind: "subheading",
          text: "Essential cookies"
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "Essential cookies are needed for the site to work and to remember your privacy choices. This includes a first-party cookie named \"soo-cookie-consent\", which records whether you have accepted or declined analytics so we can respect your choice on future visits. Because this cookie exists to honour your preferences and keep the site functioning, it is always active and does not require separate consent."
            }
          ]
        },
        {
          kind: "subheading",
          text: "Non-essential analytics"
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "Non-essential cookies and scripts support website analytics. They are off by default and load only after you accept them through the cookie banner. If you decline, they are not loaded."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "We use the following third-party services on the site:"
            }
          ]
        },
        {
          kind: "definitions",
          entries: [
            {
              term: "Vercel",
              runs: [
                {
                  text: "Hosts the website and provides Web Analytics and Speed Insights, which give us aggregate, non-identifying information about site traffic and performance. Analytics run only after you consent. See "
                },
                {
                  text: "Vercel's privacy policy",
                  href: "https://vercel.com/legal/privacy-policy"
                },
                {
                  text: "."
                }
              ]
            },
            {
              term: "Resend",
              runs: [
                {
                  text: "Delivers your form submission to us by email so we can respond. See "
                },
                {
                  text: "Resend's privacy policy",
                  href: "https://resend.com/legal/privacy-policy"
                },
                {
                  text: "."
                }
              ]
            },
            {
              term: "Cloudflare Turnstile",
              runs: [
                {
                  text: "Protects the form against spam and automated abuse without using intrusive tracking. See "
                },
                {
                  text: "Cloudflare's privacy policy",
                  href: "https://www.cloudflare.com/privacypolicy/"
                },
                {
                  text: "."
                }
              ]
            },
            {
              term: "Google Maps",
              runs: [
                {
                  text: "If a service-area map is shown, it is embedded from Google Maps, and Google may receive technical information such as your IP address to display it. See "
                },
                {
                  text: "Google's privacy policy",
                  href: "https://policies.google.com/privacy"
                },
                {
                  text: "."
                }
              ]
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "You can change your analytics choice at any time using the cookie banner. You can also block or delete cookies through your browser settings, though doing so may affect how parts of the site work."
            }
          ]
        }
      ]
    },
    {
      id: "service-providers-transfers",
      heading: "Service Providers and Cross-Border Transfers",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "We share limited personal information with the service providers listed above so they can perform services on our behalf, such as hosting the site, delivering your form submission to us, protecting against spam, and providing analytics. These providers may only use the information to provide their service to us and are required to protect it."
            }
          ]
        },
        {
          kind: "note",
          runs: [
            {
              text: "We do not sell your personal information, and we do not rent or trade it for marketing purposes."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "Some of our service providers store or process personal information outside Canada, including in the United States. The providers we use for hosting and analytics (Vercel), email delivery of your form submission (Resend), bot protection (Cloudflare Turnstile), and the map embed (Google) are among those that may process data in the United States. When information is held in another country, it may be accessible to the courts, law enforcement, and national security authorities of that country under their laws, including through lawful access requests, and those laws may differ from Canada's. We use reputable providers and rely on contractual and technical protections to keep your information safe wherever it is processed."
            }
          ]
        }
      ]
    },
    {
      id: "retention",
      heading: "Data Retention",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "We keep personal information only as long as we need it to fulfil the purposes described in this policy or as required by law, after which we securely delete or anonymize it."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "Our standard retention period for information submitted through the website is "
            },
            {
              fact: "retentionPeriod"
            },
            {
              text: ". Where a longer period is required to meet a legal, accounting, or regulatory obligation, we retain the information for that period and no longer."
            }
          ]
        }
      ]
    },
    {
      id: "safeguards",
      heading: "Security Safeguards",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "We protect personal information with safeguards appropriate to its sensitivity. These include:"
            }
          ]
        },
        {
          kind: "list",
          ordered: false,
          items: [
            [
              {
                text: "encryption of data in transit using industry-standard protocols;"
              }
            ],
            [
              {
                text: "access controls that limit who can view your information to those who need it to do their job;"
              }
            ],
            [
              {
                text: "spam and bot protection on the form to reduce abuse; and"
              }
            ],
            [
              {
                text: "the use of vetted, reputable service providers who maintain their own security measures."
              }
            ]
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "No website or method of transmission or storage is perfectly secure. While we work to protect your information, we cannot guarantee absolute security. If a breach of security safeguards creates a real risk of significant harm to you, we will notify you and report to the Office of the Privacy Commissioner of Canada as required by PIPEDA, and we will keep records of breaches as the law requires. If you believe your information has been compromised, please contact our Privacy Officer."
            }
          ]
        }
      ]
    },
    {
      id: "your-rights",
      heading: "Your Privacy Rights",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "Subject to certain legal exceptions, you have the right to:"
            }
          ]
        },
        {
          kind: "list",
          ordered: false,
          items: [
            [
              {
                text: "access the personal information we hold about you and ask how it has been used and disclosed;"
              }
            ],
            [
              {
                text: "ask us to correct information that is inaccurate or incomplete; and"
              }
            ],
            [
              {
                text: "withdraw your consent to our use of your information, subject to legal and contractual limits."
              }
            ]
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "Depending on where you live, a provincial privacy law may give you additional rights, such as data portability or the ability to ask that certain information be de-indexed. Residents of "
            },
            {
              fact: "province"
            },
            {
              text: " or another province may also be able to deal with a provincial regulator, such as Quebec's Commission d'accès à l'information or the Information and Privacy Commissioner in British Columbia or Alberta."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "To exercise any of these rights, contact our Privacy Officer using the details in the Contact section. We will respond within the timeframes required by law and may need to verify your identity before acting on your request."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "If you are not satisfied with how we have handled your personal information, you have the right to complain to the "
            },
            {
              text: "Office of the Privacy Commissioner of Canada",
              href: "https://www.priv.gc.ca/"
            },
            {
              text: ". You can reach its public enquiries line at "
            },
            {
              text: "1-800-282-1376",
              href: "tel:1-800-282-1376"
            },
            {
              text: ". A provincial privacy regulator may also have authority over your complaint depending on where you live."
            }
          ]
        }
      ]
    },
    {
      id: "childrens-privacy",
      heading: "Children's Privacy",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "Our website and services are intended for adults arranging security systems for their property. They are not directed to children, and we do not knowingly collect personal information from children. If you believe a child has provided us with personal information, please contact our Privacy Officer and we will take reasonable steps to delete it."
            }
          ]
        }
      ]
    },
    {
      id: "third-party-links",
      heading: "Links to Third-Party Sites",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "Our website may link to third-party sites, and it references brands such as Lorex, Hikvision, and HiLook, which are trademarks of their respective owners. We are an authorized partner and installer, not the owner of those brands."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "We are not responsible for the privacy practices or content of any website we do not operate. When you follow a link to another site, we encourage you to review that site's own privacy policy before providing any personal information."
            }
          ]
        }
      ]
    },
    {
      id: "changes",
      heading: "Changes to This Policy",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "We may update this Privacy Policy from time to time to reflect changes in our practices, technology, or legal requirements. The \"last updated\" date shown with this policy indicates when the current version took effect."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "We will post any changes on this page. If the changes are material, we will make the update clear so you can review what has changed before continuing to use the site."
            }
          ]
        }
      ]
    },
    {
      id: "contact",
      heading: "Contact Us",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "If you have questions about this policy, want to exercise your privacy rights, or wish to make a complaint, please contact our Privacy Officer:"
            }
          ]
        },
        {
          kind: "definitions",
          entries: [
            {
              term: "Privacy Officer",
              runs: [
                {
                  fact: "privacyOfficerName"
                }
              ]
            },
            {
              term: "Email",
              runs: [
                {
                  fact: "privacyOfficerEmail"
                }
              ]
            },
            {
              term: "Phone",
              runs: [
                {
                  fact: "privacyOfficerPhone"
                }
              ]
            },
            {
              term: "Mailing address",
              runs: [
                {
                  fact: "registeredAddress"
                }
              ]
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "We will acknowledge your request and respond within the timeframes required by applicable privacy law."
            }
          ]
        }
      ]
    }
  ]
};
