// Generated by scripts/gen-legal-content.mjs from scripts/legal-content-data.json — edit there, not here.
import type { LegalDocument } from "@/types";
import { legalLastUpdated } from "./legal-facts";

export const termsAndConditions: LegalDocument = {
  title: "Terms & Conditions",
  summary: "These Terms govern your use of the Soo Solutions Inc website, an informational site for security camera supply and installation; quotes shown here are not binding, and actual work is covered by separate written agreements.",
  lastUpdated: legalLastUpdated,
  sections: [
    {
      id: "acceptance",
      heading: "Acceptance of These Terms",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "These Terms & Conditions (the "
            },
            {
              text: "\"Terms\""
            },
            {
              text: ") govern your access to and use of the website operated by "
            },
            {
              fact: "entityName"
            },
            {
              text: " (\"we\", \"us\", or \"our\"). By visiting or using this website, you confirm that you have read these Terms and agree to be bound by them."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "If you do not agree with any part of these Terms, please do not use the website. Your continued use of the site is taken as your ongoing acceptance of the version of these Terms in effect at the time."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "These Terms work alongside our "
            },
            {
              text: "Privacy Policy",
              href: "/privacy"
            },
            {
              text: ", which explains how we handle personal information you provide through the site."
            }
          ]
        }
      ]
    },
    {
      id: "about-services",
      heading: "About This Website & Our Services",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "This is an informational marketing website. It tells you about "
            },
            {
              fact: "entityName"
            },
            {
              text: " and the security camera and CCTV supply and installation services we offer for commercial and residential properties. It also lets you request a quote or contact us through our online form."
            }
          ]
        },
        {
          kind: "note",
          runs: [
            {
              text: "Any quote, estimate, price, or specification shown on this website or generated from our contact form is for information only. It is not an offer, and it is not a binding contract. Figures may change after we assess your property and confirm scope, equipment, and site conditions."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "Our actual supply and installation work, and any product warranties, are covered by separate written agreements signed by you and us. Those agreements, not this website, set out the terms of the work we perform, pricing, timelines, and warranty coverage. If anything on this website appears to conflict with a signed service agreement, the signed agreement controls."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "Submitting the contact or quote form does not create any obligation on either side. It simply starts a conversation. A contract is formed only when both parties sign a written service agreement."
            }
          ]
        }
      ]
    },
    {
      id: "eligibility",
      heading: "Eligibility",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "To use this website and to submit a request through our form, you must be old enough to enter into a binding contract under the laws of your province or territory, which generally means you have reached the age of majority where you live."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "If you are using the website on behalf of a business or another person, you confirm that you are authorized to act for them and to accept these Terms on their behalf."
            }
          ]
        }
      ]
    },
    {
      id: "intellectual-property",
      heading: "Intellectual Property",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "The content on this website, including the text, page design, layout, graphics, photographs, and our logos, is owned by "
            },
            {
              fact: "entityName"
            },
            {
              text: " or by our licensors, and is protected by Canadian and international intellectual property laws."
            }
          ]
        },
        {
          kind: "subheading",
          text: "Third-party brands"
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "We reference equipment brands such as Lorex, Hikvision, and HiLook because we supply and install their products. Those names, logos, and trademarks belong to their respective owners. "
            },
            {
              fact: "entityName"
            },
            {
              text: " is an authorized partner and installer of these products. We are not the brand owner, and our use of these names does not imply that the brand owners endorse or are affiliated with our website beyond that supplier relationship."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "You may view and read this website for your own personal, non-commercial purposes. We do not grant you any other licence or right. You may not copy, reproduce, republish, distribute, or create derivative works from our content without our prior written permission, except where the law allows."
            }
          ]
        }
      ]
    },
    {
      id: "acceptable-use",
      heading: "Acceptable Use",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "You agree to use this website lawfully and respectfully. In particular, you agree that you will not:"
            }
          ]
        },
        {
          kind: "list",
          ordered: false,
          items: [
            [
              {
                text: "Use the website for any unlawful purpose or in a way that breaches any applicable law or regulation."
              }
            ],
            [
              {
                text: "Scrape, harvest, crawl, or otherwise collect data from the website using automated tools, except for legitimate search-engine indexing."
              }
            ],
            [
              {
                text: "Interfere with or disrupt the website, its servers, or its security, or attempt to gain unauthorized access to any part of it or its underlying systems."
              }
            ],
            [
              {
                text: "Submit content that infringes anyone's rights, or that is false, misleading, defamatory, harmful, or malicious, including malware or other harmful code."
              }
            ],
            [
              {
                text: "Misuse the contact or quote form, for example by sending spam, submitting another person's information without their permission, or impersonating someone else."
              }
            ]
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "We may restrict or block access to the website if we reasonably believe you have breached these Terms."
            }
          ]
        }
      ]
    },
    {
      id: "third-party-links-brands",
      heading: "Third-Party Links & Brand References",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "This website may link to third-party websites, may embed a Google Maps view to show our service area, and may mention third-party products and brands. We provide these links and references for your convenience and information only."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "We do not control third-party websites or services, and we are not responsible for their content, accuracy, availability, products, or privacy practices. A link or brand reference on our site does not mean we endorse that third party, and it does not create any partnership between us and them beyond what we describe. When you leave our website, the terms and privacy policy of the third party apply."
            }
          ]
        }
      ]
    },
    {
      id: "disclaimers",
      heading: "Disclaimers",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "The website is provided on an \"as is\" and \"as available\" basis. While we try to keep the information accurate and current, we make no warranty or representation that the content is complete, accurate, up to date, or error free, or that the website will always be available, uninterrupted, or secure."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "Information on this website is general in nature and does not amount to professional or technical advice for your specific property. Any final recommendation depends on an on-site assessment."
            }
          ]
        },
        {
          kind: "note",
          runs: [
            {
              text: "Nothing on this website is a warranty for any product or installation. Product warranties and installation warranties are provided only through separate written agreements. This disclaimer does not exclude or limit any warranty or right that cannot be excluded or limited under applicable Canadian consumer protection law."
            }
          ]
        }
      ]
    },
    {
      id: "limitation-of-liability",
      heading: "Limitation of Liability",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "To the fullest extent permitted by law, "
            },
            {
              fact: "entityName"
            },
            {
              text: ", and its directors, officers, employees, and contractors, will not be liable for any indirect, incidental, special, consequential, or punitive damages, or for any loss of profits, revenue, data, or goodwill, arising out of or relating to your use of, or inability to use, this website."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "Where liability cannot lawfully be excluded but can be limited, our total liability arising from or relating to your use of the website (and excluding any matter governed by a separate written service agreement) is limited to one hundred Canadian dollars (CAD $100)."
            }
          ]
        },
        {
          kind: "note",
          runs: [
            {
              text: "Nothing in these Terms excludes or limits liability that cannot be excluded or limited under applicable law, such as liability for death or personal injury caused by negligence, for fraud, or under consumer protection legislation. Liability connected to actual supply and installation work is dealt with in the separate written service agreement, not here."
            }
          ]
        }
      ]
    },
    {
      id: "indemnification",
      heading: "Indemnification",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "You agree to indemnify and hold harmless "
            },
            {
              fact: "entityName"
            },
            {
              text: ", and its directors, officers, employees, and contractors, from any claims, demands, losses, liabilities, and reasonable legal costs that arise out of or relate to your misuse of the website, your breach of these Terms, or your violation of any law or third-party right in connection with your use of the website. This obligation continues even after you stop using the website."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "Nothing in this section requires you to indemnify us to an extent prohibited by applicable consumer protection law."
            }
          ]
        }
      ]
    },
    {
      id: "privacy",
      heading: "Privacy",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "Your use of this website is also governed by our "
            },
            {
              text: "Privacy Policy",
              href: "/privacy"
            },
            {
              text: ", which explains what personal information we collect through the contact and quote form, how we use it, the cookies and analytics we use, and the sub-processors that help us run the site. Some of those sub-processors are located outside Canada, which means your information may be processed in another country and may be subject to that country's laws, including lawful access by foreign authorities."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "In line with Canada's anti-spam law (CASL), we only send commercial or marketing email where you have given express consent, we identify ourselves clearly in every message, and we include a working way to unsubscribe. The Privacy Policy sets out the full detail, and you should read it together with these Terms."
            }
          ]
        }
      ]
    },
    {
      id: "governing-law",
      heading: "Governing Law & Jurisdiction",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "These Terms, and any dispute or claim arising out of or in connection with them or your use of the website, are governed by the laws of the Province of "
            },
            {
              fact: "governingProvince"
            },
            {
              text: " and the federal laws of Canada that apply there, without regard to conflict-of-laws rules."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "You agree that the courts located in the Province of "
            },
            {
              fact: "governingProvince"
            },
            {
              text: " have non-exclusive jurisdiction to resolve any such dispute, subject to any mandatory consumer protection rights you have in your own province or territory."
            }
          ]
        }
      ]
    },
    {
      id: "changes",
      heading: "Changes to These Terms",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "We may update these Terms from time to time, for example to reflect changes to the website, our services, or the law. When we do, we will post the revised version on this page and update the \"last updated\" date shown with it."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "The version posted at the time you use the website is the one that applies. By continuing to use the website after an update takes effect, you accept the revised Terms. We encourage you to review this page periodically."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "Changes that affect how we handle your personal information are addressed separately through the update mechanism set out in our "
            },
            {
              text: "Privacy Policy",
              href: "/privacy"
            },
            {
              text: ", so you are not relying on this page alone for privacy-related updates."
            }
          ]
        }
      ]
    },
    {
      id: "severability-entire-agreement",
      heading: "Severability & Entire Agreement",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "If any provision of these Terms is found to be invalid or unenforceable, that provision will be limited or removed to the minimum extent necessary, and the remaining provisions will stay in full force and effect."
            }
          ]
        },
        {
          kind: "paragraph",
          runs: [
            {
              text: "These Terms, together with our "
            },
            {
              text: "Privacy Policy",
              href: "/privacy"
            },
            {
              text: " and any separate written service agreements between you and us, make up the entire agreement between you and "
            },
            {
              fact: "entityName"
            },
            {
              text: " regarding your use of this website, and they replace any earlier understanding on that subject."
            }
          ]
        }
      ]
    },
    {
      id: "contact",
      heading: "Contact Us",
      blocks: [
        {
          kind: "paragraph",
          runs: [
            {
              text: "If you have any questions about these Terms, please reach out to us:"
            }
          ]
        },
        {
          kind: "definitions",
          entries: [
            {
              term: "Company",
              runs: [
                {
                  fact: "entityName"
                }
              ]
            },
            {
              term: "Mailing address",
              runs: [
                {
                  fact: "registeredAddress"
                }
              ]
            },
            {
              term: "Email",
              runs: [
                {
                  fact: "privacyOfficerEmail"
                }
              ]
            },
            {
              term: "Phone",
              runs: [
                {
                  fact: "privacyOfficerPhone"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
};
